import { createRouter, createWebHistory } from 'vue-router'
import ThemeSwitcher from '../components/ThemeSwitcher.vue'

const routes = [
  { path: '/login', component: () => import('../components/Login.vue') },
  {
    path: '/',
    component: ThemeSwitcher,
    redirect: '/home',
    meta: { requiresAuth: true },
    children: [
      { path: 'home', name: 'Home', component: () => import('../components/Dashboard.vue') },
      { path: 'menu', name: 'MenuManagement', component: () => import('../components/MenuManagement.vue') },
      { path: 'config', name: 'ConfigManagement', component: () => import('../components/ConfigManagement.vue') },
            { path: 'product_product_list', name: 'ProductProductList', component: () => import('../components/generated/ProductProductList.vue') },
      { path: 'product_product_classify', name: 'ProductProductClassify', component: () => import('../components/generated/ProductProductClassify.vue') },
      { path: 'product_add_product', name: 'ProductAddProduct', component: () => import('../components/generated/ProductAddProduct.vue') },
      { path: 'product_product_attr', name: 'ProductProductAttr', component: () => import('../components/generated/ProductProductAttr.vue') },
      { path: 'product_label', name: 'ProductLabel', component: () => import('../components/generated/ProductLabel.vue') },
      { path: 'product_product_brand', name: 'ProductProductBrand', component: () => import('../components/generated/ProductProductBrand.vue') },
      { path: 'product_category_params', name: 'ProductCategoryParams', component: () => import('../components/generated/ProductCategoryParams.vue') },
      { path: 'product_unitList', name: 'ProductUnitlist', component: () => import('../components/generated/ProductUnitlist.vue') },
      { path: 'product_specs', name: 'ProductSpecs', component: () => import('../components/generated/ProductSpecs.vue') },
      { path: 'product_ensure_create', name: 'ProductEnsureCreate', component: () => import('../components/generated/ProductEnsureCreate.vue') },
      { path: 'setting_system_create', name: 'SettingSystemCreate', component: () => import('../components/generated/SettingSystemCreate.vue') },
      { path: 'setting_system_form_data', name: 'SettingSystemFormData', component: () => import('../components/generated/SettingSystemFormData.vue') },
      { path: 'product_product_reply', name: 'ProductProductReply', component: () => import('../components/generated/ProductProductReply.vue') },
      { path: 'product_product_reply_config', name: 'ProductProductReplyConfig', component: () => import('../components/generated/ProductProductReplyConfig.vue') },
      { path: 'adminorder_list', name: 'AdminorderList', component: () => import('../components/generated/AdminorderList.vue') },
      { path: 'order_refund', name: 'OrderRefund', component: () => import('../components/generated/OrderRefund.vue') },
      { path: 'setting_distribution_deliver', name: 'SettingDistributionDeliver', component: () => import('../components/generated/SettingDistributionDeliver.vue') },
      { path: 'setting_freight_shipping_templates_list', name: 'SettingFreightShippingTemplatesList', component: () => import('../components/generated/SettingFreightShippingTemplatesList.vue') },
      { path: 'setting_freight_express_index', name: 'SettingFreightExpressIndex', component: () => import('../components/generated/SettingFreightExpressIndex.vue') },
      { path: 'setting_delivery_service_index', name: 'SettingDeliveryServiceIndex', component: () => import('../components/generated/SettingDeliveryServiceIndex.vue') },
      { path: 'setting_shop_storeList', name: 'SettingShopStorelist', component: () => import('../components/generated/SettingShopStorelist.vue') },
      { path: 'setting_city_delivery_setting', name: 'SettingCityDeliverySetting', component: () => import('../components/generated/SettingCityDeliverySetting.vue') },
      { path: 'setting_city_delivery_record', name: 'SettingCityDeliveryRecord', component: () => import('../components/generated/SettingCityDeliveryRecord.vue') },
      { path: 'setting_freight_city_list', name: 'SettingFreightCityList', component: () => import('../components/generated/SettingFreightCityList.vue') },
      { path: 'setting_shop_product', name: 'SettingShopProduct', component: () => import('../components/generated/SettingShopProduct.vue') },
      { path: 'setting_shop_trade', name: 'SettingShopTrade', component: () => import('../components/generated/SettingShopTrade.vue') },
      { path: 'setting_shop_agreemant', name: 'SettingShopAgreemant', component: () => import('../components/generated/SettingShopAgreemant.vue') },
      { path: 'setting_shop_releaseset', name: 'SettingShopReleaseset', component: () => import('../components/generated/SettingShopReleaseset.vue') },
      { path: 'setting_shop_coinoffset', name: 'SettingShopCoinoffset', component: () => import('../components/generated/SettingShopCoinoffset.vue') },
      { path: 'statistic_user', name: 'StatisticUser', component: () => import('../components/generated/StatisticUser.vue') },
      { path: 'user_list', name: 'UserList', component: () => import('../components/generated/UserList.vue') },
      { path: 'user_group', name: 'UserGroup', component: () => import('../components/generated/UserGroup.vue') },
      { path: 'user_label_create', name: 'UserLabelCreate', component: () => import('../components/generated/UserLabelCreate.vue') },
      { path: 'marketing_channel_code_create', name: 'MarketingChannelCodeCreate', component: () => import('../components/generated/MarketingChannelCodeCreate.vue') },
      { path: 'user_userSet', name: 'UserUserset', component: () => import('../components/generated/UserUserset.vue') },
      { path: 'vipuser_level_list', name: 'VipuserLevelList', component: () => import('../components/generated/VipuserLevelList.vue') },
      { path: 'user_levelSet', name: 'UserLevelset', component: () => import('../components/generated/UserLevelset.vue') },
      { path: 'user_registerSet', name: 'UserRegisterset', component: () => import('../components/generated/UserRegisterset.vue') },
      { path: 'user_memberGift', name: 'UserMembergift', component: () => import('../components/generated/UserMembergift.vue') },
      { path: 'marketing_store_coupon_issue_create', name: 'MarketingStoreCouponIssueCreate', component: () => import('../components/generated/MarketingStoreCouponIssueCreate.vue') },
      { path: 'marketing_store_coupon_user_index', name: 'MarketingStoreCouponUserIndex', component: () => import('../components/generated/MarketingStoreCouponUserIndex.vue') },
      { path: 'marketing_integral_system_config', name: 'MarketingIntegralSystemConfig', component: () => import('../components/generated/MarketingIntegralSystemConfig.vue') },
      { path: 'marketing_user_point_index', name: 'MarketingUserPointIndex', component: () => import('../components/generated/MarketingUserPointIndex.vue') },
      { path: 'marketing_balance_recharge', name: 'MarketingBalanceRecharge', component: () => import('../components/generated/MarketingBalanceRecharge.vue') },
      { path: 'integral_release_index', name: 'IntegralReleaseIndex', component: () => import('../components/generated/IntegralReleaseIndex.vue') },
      { path: 'marketing_weather_tpapply', name: 'MarketingWeatherTpapply', component: () => import('../components/generated/MarketingWeatherTpapply.vue') },
      { path: 'marketing_weather_tongpiao', name: 'MarketingWeatherTongpiao', component: () => import('../components/generated/MarketingWeatherTongpiao.vue') },
      { path: 'work_channel_code', name: 'WorkChannelCode', component: () => import('../components/generated/WorkChannelCode.vue') },
      { path: 'work_welcome', name: 'WorkWelcome', component: () => import('../components/generated/WorkWelcome.vue') },
      { path: 'work_createCode', name: 'WorkCreatecode', component: () => import('../components/generated/WorkCreatecode.vue') },
      { path: 'work_addWelcome', name: 'WorkAddwelcome', component: () => import('../components/generated/WorkAddwelcome.vue') },
      { path: 'work_client_list', name: 'WorkClientList', component: () => import('../components/generated/WorkClientList.vue') },
      { path: 'work_client_group', name: 'WorkClientGroup', component: () => import('../components/generated/WorkClientGroup.vue') },
      { path: 'work_client_add_group', name: 'WorkClientAddGroup', component: () => import('../components/generated/WorkClientAddGroup.vue') },
      { path: 'work_client_add_moment', name: 'WorkClientAddMoment', component: () => import('../components/generated/WorkClientAddMoment.vue') },
      { path: 'work_client_moment', name: 'WorkClientMoment', component: () => import('../components/generated/WorkClientMoment.vue') },
      { path: 'work_client_group_info', name: 'WorkClientGroupInfo', component: () => import('../components/generated/WorkClientGroupInfo.vue') },
      { path: 'work_client_moment_info', name: 'WorkClientMomentInfo', component: () => import('../components/generated/WorkClientMomentInfo.vue') },
      { path: 'work_client_group_chat', name: 'WorkClientGroupChat', component: () => import('../components/generated/WorkClientGroupChat.vue') },
      { path: 'work_auth_group', name: 'WorkAuthGroup', component: () => import('../components/generated/WorkAuthGroup.vue') },
      { path: 'work_addAuthGroup', name: 'WorkAddauthgroup', component: () => import('../components/generated/WorkAddauthgroup.vue') },
      { path: 'work_client_statistical', name: 'WorkClientStatistical', component: () => import('../components/generated/WorkClientStatistical.vue') },
      { path: 'work_group_template', name: 'WorkGroupTemplate', component: () => import('../components/generated/WorkGroupTemplate.vue') },
      { path: 'work_group_add_template', name: 'WorkGroupAddTemplate', component: () => import('../components/generated/WorkGroupAddTemplate.vue') },
      { path: 'work_group_template_info', name: 'WorkGroupTemplateInfo', component: () => import('../components/generated/WorkGroupTemplateInfo.vue') },
      { path: 'work_staffList', name: 'WorkStafflist', component: () => import('../components/generated/WorkStafflist.vue') },
      { path: 'user_importRecord', name: 'UserImportrecord', component: () => import('../components/generated/UserImportrecord.vue') },
      { path: 'marketing_home', name: 'MarketingHome', component: () => import('../components/generated/MarketingHome.vue') },
      { path: 'vipuser_grade_type', name: 'VipuserGradeType', component: () => import('../components/generated/VipuserGradeType.vue') },
      { path: 'vipuser_grade_right', name: 'VipuserGradeRight', component: () => import('../components/generated/VipuserGradeRight.vue') },
      { path: 'vipuser_grade_agreement', name: 'VipuserGradeAgreement', component: () => import('../components/generated/VipuserGradeAgreement.vue') },
      { path: 'vipuser_grade_card', name: 'VipuserGradeCard', component: () => import('../components/generated/VipuserGradeCard.vue') },
      { path: 'vipuser_grade_record', name: 'VipuserGradeRecord', component: () => import('../components/generated/VipuserGradeRecord.vue') },
      { path: 'vipuser_grade_list', name: 'VipuserGradeList', component: () => import('../components/generated/VipuserGradeList.vue') },
      { path: 'user_svipSet', name: 'UserSvipset', component: () => import('../components/generated/UserSvipset.vue') },
      { path: 'marketing_lottery_create', name: 'MarketingLotteryCreate', component: () => import('../components/generated/MarketingLotteryCreate.vue') },
      { path: 'marketing_lottery_recording_list', name: 'MarketingLotteryRecordingList', component: () => import('../components/generated/MarketingLotteryRecordingList.vue') },
      { path: 'marketing_lottery_config', name: 'MarketingLotteryConfig', component: () => import('../components/generated/MarketingLotteryConfig.vue') },
      { path: 'marketing_store_combination_index', name: 'MarketingStoreCombinationIndex', component: () => import('../components/generated/MarketingStoreCombinationIndex.vue') },
      { path: 'marketing_store_combination_combina_list', name: 'MarketingStoreCombinationCombinaList', component: () => import('../components/generated/MarketingStoreCombinationCombinaList.vue') },
      { path: 'marketing_store_combination_create', name: 'MarketingStoreCombinationCreate', component: () => import('../components/generated/MarketingStoreCombinationCreate.vue') },
      { path: 'marketing_store_combination_statistics', name: 'MarketingStoreCombinationStatistics', component: () => import('../components/generated/MarketingStoreCombinationStatistics.vue') },
      { path: 'marketing_store_seckill_list', name: 'MarketingStoreSeckillList', component: () => import('../components/generated/MarketingStoreSeckillList.vue') },
      { path: 'marketing_store_seckill_statistics', name: 'MarketingStoreSeckillStatistics', component: () => import('../components/generated/MarketingStoreSeckillStatistics.vue') },
      { path: 'marketing_store_seckill_create', name: 'MarketingStoreSeckillCreate', component: () => import('../components/generated/MarketingStoreSeckillCreate.vue') },
      { path: 'marketing_store_seckill_data_index', name: 'MarketingStoreSeckillDataIndex', component: () => import('../components/generated/MarketingStoreSeckillDataIndex.vue') },
      { path: 'marketing_store_bargain_index', name: 'MarketingStoreBargainIndex', component: () => import('../components/generated/MarketingStoreBargainIndex.vue') },
      { path: 'marketing_store_bargain_create', name: 'MarketingStoreBargainCreate', component: () => import('../components/generated/MarketingStoreBargainCreate.vue') },
      { path: 'marketing_store_bargain_bargain_list', name: 'MarketingStoreBargainBargainList', component: () => import('../components/generated/MarketingStoreBargainBargainList.vue') },
      { path: 'marketing_store_bargain_setting', name: 'MarketingStoreBargainSetting', component: () => import('../components/generated/MarketingStoreBargainSetting.vue') },
      { path: 'marketing_store_bargain_statistics', name: 'MarketingStoreBargainStatistics', component: () => import('../components/generated/MarketingStoreBargainStatistics.vue') },
      { path: 'marketing_giftCard_manage', name: 'MarketingGiftcardManage', component: () => import('../components/generated/MarketingGiftcardManage.vue') },
      { path: 'marketing_giftCard_index', name: 'MarketingGiftcardIndex', component: () => import('../components/generated/MarketingGiftcardIndex.vue') },
      { path: 'marketing_giftCard_record', name: 'MarketingGiftcardRecord', component: () => import('../components/generated/MarketingGiftcardRecord.vue') },
      { path: 'marketing_giftCard_create', name: 'MarketingGiftcardCreate', component: () => import('../components/generated/MarketingGiftcardCreate.vue') },
      { path: 'marketing_automation', name: 'MarketingAutomation', component: () => import('../components/generated/MarketingAutomation.vue') },
      { path: 'marketing_automation_create', name: 'MarketingAutomationCreate', component: () => import('../components/generated/MarketingAutomationCreate.vue') },
      { path: 'marketing_birthday', name: 'MarketingBirthday', component: () => import('../components/generated/MarketingBirthday.vue') },
      { path: 'marketing_discount_add', name: 'MarketingDiscountAdd', component: () => import('../components/generated/MarketingDiscountAdd.vue') },
      { path: 'marketing_discount_add_discount', name: 'MarketingDiscountAddDiscount', component: () => import('../components/generated/MarketingDiscountAddDiscount.vue') },
      { path: 'marketing_discount_add_give', name: 'MarketingDiscountAddGive', component: () => import('../components/generated/MarketingDiscountAddGive.vue') },
      { path: 'marketing_discount_add_pieces', name: 'MarketingDiscountAddPieces', component: () => import('../components/generated/MarketingDiscountAddPieces.vue') },
      { path: 'marketing_store_discounts_create', name: 'MarketingStoreDiscountsCreate', component: () => import('../components/generated/MarketingStoreDiscountsCreate.vue') },
      { path: 'marketing_integral_classify', name: 'MarketingIntegralClassify', component: () => import('../components/generated/MarketingIntegralClassify.vue') },
      { path: 'marketing_store_integral_index', name: 'MarketingStoreIntegralIndex', component: () => import('../components/generated/MarketingStoreIntegralIndex.vue') },
      { path: 'marketing_store_integral_create', name: 'MarketingStoreIntegralCreate', component: () => import('../components/generated/MarketingStoreIntegralCreate.vue') },
      { path: 'pages_marketing_store_integral_add_store_integral', name: 'PagesMarketingStoreIntegralAddStoreIntegral', component: () => import('../components/generated/PagesMarketingStoreIntegralAddStoreIntegral.vue') },
      { path: 'marketing_point_statistic', name: 'MarketingPointStatistic', component: () => import('../components/generated/MarketingPointStatistic.vue') },
      { path: 'marketing_sign_config', name: 'MarketingSignConfig', component: () => import('../components/generated/MarketingSignConfig.vue') },
      { path: 'marketing_sign_rewards', name: 'MarketingSignRewards', component: () => import('../components/generated/MarketingSignRewards.vue') },
      { path: 'marketing_activity_frame_create', name: 'MarketingActivityFrameCreate', component: () => import('../components/generated/MarketingActivityFrameCreate.vue') },
      { path: 'marketing_activity_background_create', name: 'MarketingActivityBackgroundCreate', component: () => import('../components/generated/MarketingActivityBackgroundCreate.vue') },
      { path: 'agent_agent_manage_index', name: 'AgentAgentManageIndex', component: () => import('../components/generated/AgentAgentManageIndex.vue') },
      { path: 'setting_membership_level_index', name: 'SettingMembershipLevelIndex', component: () => import('../components/generated/SettingMembershipLevelIndex.vue') },
      { path: 'finance_finance_commission', name: 'FinanceFinanceCommission', component: () => import('../components/generated/FinanceFinanceCommission.vue') },
      { path: 'agent_promoter_apply', name: 'AgentPromoterApply', component: () => import('../components/generated/AgentPromoterApply.vue') },
      { path: 'setting_system_config_retail_2_9', name: 'SettingSystemConfigRetail29', component: () => import('../components/generated/SettingSystemConfigRetail29.vue') },
      { path: 'setting_system_config_rake_back', name: 'SettingSystemConfigRakeBack', component: () => import('../components/generated/SettingSystemConfigRakeBack.vue') },
      { path: 'agent_agreement', name: 'AgentAgreement', component: () => import('../components/generated/AgentAgreement.vue') },
      { path: 'agent_division_list', name: 'AgentDivisionList', component: () => import('../components/generated/AgentDivisionList.vue') },
      { path: 'agent_agent_list', name: 'AgentAgentList', component: () => import('../components/generated/AgentAgentList.vue') },
      { path: 'agent_apply_list', name: 'AgentApplyList', component: () => import('../components/generated/AgentApplyList.vue') },
      { path: 'setting_shop_division', name: 'SettingShopDivision', component: () => import('../components/generated/SettingShopDivision.vue') },
      { path: 'agent_statistics', name: 'AgentStatistics', component: () => import('../components/generated/AgentStatistics.vue') },
      { path: 'agent_order', name: 'AgentOrder', component: () => import('../components/generated/AgentOrder.vue') },
      { path: 'setting_pages_devise', name: 'SettingPagesDevise', component: () => import('../components/generated/SettingPagesDevise.vue') },
      { path: 'setting_theme_style', name: 'SettingThemeStyle', component: () => import('../components/generated/SettingThemeStyle.vue') },
      { path: 'setting_pages_product_category', name: 'SettingPagesProductCategory', component: () => import('../components/generated/SettingPagesProductCategory.vue') },
      { path: 'setting_pages_home', name: 'SettingPagesHome', component: () => import('../components/generated/SettingPagesHome.vue') },
      { path: 'setting_pages_product_detail', name: 'SettingPagesProductDetail', component: () => import('../components/generated/SettingPagesProductDetail.vue') },
      { path: 'setting_pages_fab', name: 'SettingPagesFab', component: () => import('../components/generated/SettingPagesFab.vue') },
      { path: 'setting_system_visualization_data', name: 'SettingSystemVisualizationData', component: () => import('../components/generated/SettingSystemVisualizationData.vue') },
      { path: 'product_hotWords', name: 'ProductHotwords', component: () => import('../components/generated/ProductHotwords.vue') },
      { path: 'system_file', name: 'SystemFile', component: () => import('../components/generated/SystemFile.vue') },
      { path: 'content_community_topic', name: 'ContentCommunityTopic', component: () => import('../components/generated/ContentCommunityTopic.vue') },
      { path: 'content_community_addContent', name: 'ContentCommunityAddcontent', component: () => import('../components/generated/ContentCommunityAddcontent.vue') },
      { path: 'content_community_comment', name: 'ContentCommunityComment', component: () => import('../components/generated/ContentCommunityComment.vue') },
      { path: 'content_community_setting', name: 'ContentCommunitySetting', component: () => import('../components/generated/ContentCommunitySetting.vue') },
      { path: 'content_article_category_index', name: 'ContentArticleCategoryIndex', component: () => import('../components/generated/ContentArticleCategoryIndex.vue') },
      { path: 'content_article_index', name: 'ContentArticleIndex', component: () => import('../components/generated/ContentArticleIndex.vue') },
      { path: 'content_article_add_article', name: 'ContentArticleAddArticle', component: () => import('../components/generated/ContentArticleAddArticle.vue') },
      { path: 'setting_store_service_index', name: 'SettingStoreServiceIndex', component: () => import('../components/generated/SettingStoreServiceIndex.vue') },
      { path: 'setting_store_service_speechcraft', name: 'SettingStoreServiceSpeechcraft', component: () => import('../components/generated/SettingStoreServiceSpeechcraft.vue') },
      { path: 'setting_store_service_feedback', name: 'SettingStoreServiceFeedback', component: () => import('../components/generated/SettingStoreServiceFeedback.vue') },
      { path: 'kefu_setup', name: 'KefuSetup', component: () => import('../components/generated/KefuSetup.vue') },
      { path: 'supplier_menu_list', name: 'SupplierMenuList', component: () => import('../components/generated/SupplierMenuList.vue') },
      { path: 'supplier_apply', name: 'SupplierApply', component: () => import('../components/generated/SupplierApply.vue') },
      { path: 'supplier_orderList_index', name: 'SupplierOrderlistIndex', component: () => import('../components/generated/SupplierOrderlistIndex.vue') },
      { path: 'supplier_afterOrder_index', name: 'SupplierAfterorderIndex', component: () => import('../components/generated/SupplierAfterorderIndex.vue') },
      { path: 'supplier_orderStatistics_index', name: 'SupplierOrderstatisticsIndex', component: () => import('../components/generated/SupplierOrderstatisticsIndex.vue') },
      { path: 'supplier_supplier_index', name: 'SupplierSupplierIndex', component: () => import('../components/generated/SupplierSupplierIndex.vue') },
      { path: 'supplier_supplierAdd', name: 'SupplierSupplieradd', component: () => import('../components/generated/SupplierSupplieradd.vue') },
      { path: 'supplier_setting', name: 'SupplierSetting', component: () => import('../components/generated/SupplierSetting.vue') },
      { path: 'user_channelMerchant_examine', name: 'UserChannelmerchantExamine', component: () => import('../components/generated/UserChannelmerchantExamine.vue') },
      { path: 'user_channelMerchant_list', name: 'UserChannelmerchantList', component: () => import('../components/generated/UserChannelmerchantList.vue') },
      { path: 'user_channelMerchant_identity', name: 'UserChannelmerchantIdentity', component: () => import('../components/generated/UserChannelmerchantIdentity.vue') },
      { path: 'user_channelMerchant_setting', name: 'UserChannelmerchantSetting', component: () => import('../components/generated/UserChannelmerchantSetting.vue') },
      { path: 'order_invoice_list', name: 'OrderInvoiceList', component: () => import('../components/generated/OrderInvoiceList.vue') },
      { path: 'order_invoice_setup', name: 'OrderInvoiceSetup', component: () => import('../components/generated/OrderInvoiceSetup.vue') },
      { path: 'finance_user_extract_index', name: 'FinanceUserExtractIndex', component: () => import('../components/generated/FinanceUserExtractIndex.vue') },
      { path: 'setting_system_config_advance', name: 'SettingSystemConfigAdvance', component: () => import('../components/generated/SettingSystemConfigAdvance.vue') },
      { path: 'supplier_capital_index', name: 'SupplierCapitalIndex', component: () => import('../components/generated/SupplierCapitalIndex.vue') },
      { path: 'supplier_bill_index', name: 'SupplierBillIndex', component: () => import('../components/generated/SupplierBillIndex.vue') },
      { path: 'supplier_cash_index', name: 'SupplierCashIndex', component: () => import('../components/generated/SupplierCashIndex.vue') },
      { path: 'supplier_bill_index_1', name: 'SupplierBillIndex1', component: () => import('../components/generated/SupplierBillIndex1.vue') },
      { path: 'supplier_finance_set', name: 'SupplierFinanceSet', component: () => import('../components/generated/SupplierFinanceSet.vue') },
      { path: 'finance_user_recharge_index', name: 'FinanceUserRechargeIndex', component: () => import('../components/generated/FinanceUserRechargeIndex.vue') },
      { path: 'statistic_capital', name: 'StatisticCapital', component: () => import('../components/generated/StatisticCapital.vue') },
      { path: 'statistic', name: 'Statistic', component: () => import('../components/generated/Statistic.vue') },
      { path: 'app_wechat_base', name: 'AppWechatBase', component: () => import('../components/generated/AppWechatBase.vue') },
      { path: 'app_wechat_setting_menus_index', name: 'AppWechatSettingMenusIndex', component: () => import('../components/generated/AppWechatSettingMenusIndex.vue') },
      { path: 'app_wechat_card', name: 'AppWechatCard', component: () => import('../components/generated/AppWechatCard.vue') },
      { path: 'app_wechat_reply', name: 'AppWechatReply', component: () => import('../components/generated/AppWechatReply.vue') },
      { path: 'app_wechat_news_category_save', name: 'AppWechatNewsCategorySave', component: () => import('../components/generated/AppWechatNewsCategorySave.vue') },
      { path: 'app_routine_download', name: 'AppRoutineDownload', component: () => import('../components/generated/AppRoutineDownload.vue') },
      { path: 'content_live_add_live_room', name: 'ContentLiveAddLiveRoom', component: () => import('../components/generated/ContentLiveAddLiveRoom.vue') },
      { path: 'content_live_add_live_goods', name: 'ContentLiveAddLiveGoods', component: () => import('../components/generated/ContentLiveAddLiveGoods.vue') },
      { path: 'content_live_anchor', name: 'ContentLiveAnchor', component: () => import('../components/generated/ContentLiveAnchor.vue') },
      { path: 'app_pc', name: 'AppPc', component: () => import('../components/generated/AppPc.vue') },
      { path: 'setting_pc_group_data', name: 'SettingPcGroupData', component: () => import('../components/generated/SettingPcGroupData.vue') },
      { path: 'work_config', name: 'WorkConfig', component: () => import('../components/generated/WorkConfig.vue') },
      { path: 'setting_shop_base', name: 'SettingShopBase', component: () => import('../components/generated/SettingShopBase.vue') },
      { path: 'setting_notification_notificationEdit', name: 'SettingNotificationNotificationedit', component: () => import('../components/generated/SettingNotificationNotificationedit.vue') },
      { path: 'setting_sms_sms_config_index', name: 'SettingSmsSmsConfigIndex', component: () => import('../components/generated/SettingSmsSmsConfigIndex.vue') },
      { path: 'setting_system_config_sms', name: 'SettingSystemConfigSms', component: () => import('../components/generated/SettingSystemConfigSms.vue') },
      { path: 'setting_third_party', name: 'SettingThirdParty', component: () => import('../components/generated/SettingThirdParty.vue') },
      { path: 'setting_document', name: 'SettingDocument', component: () => import('../components/generated/SettingDocument.vue') },
      { path: 'setting_shop_pay', name: 'SettingShopPay', component: () => import('../components/generated/SettingShopPay.vue') },
      { path: 'setting_storage', name: 'SettingStorage', component: () => import('../components/generated/SettingStorage.vue') },
      { path: 'setting_document_content', name: 'SettingDocumentContent', component: () => import('../components/generated/SettingDocumentContent.vue') },
      { path: 'setting_system_role_index', name: 'SettingSystemRoleIndex', component: () => import('../components/generated/SettingSystemRoleIndex.vue') },
      { path: 'setting_system_admin_index', name: 'SettingSystemAdminIndex', component: () => import('../components/generated/SettingSystemAdminIndex.vue') },
      { path: 'setting_system_menus_index', name: 'SettingSystemMenusIndex', component: () => import('../components/generated/SettingSystemMenusIndex.vue') },
      { path: 'system_crontab_create', name: 'SystemCrontabCreate', component: () => import('../components/generated/SystemCrontabCreate.vue') },
      { path: 'system_config_system_config_tab_index', name: 'SystemConfigSystemConfigTabIndex', component: () => import('../components/generated/SystemConfigSystemConfigTabIndex.vue') },
      { path: 'system_config_system_group_index', name: 'SystemConfigSystemGroupIndex', component: () => import('../components/generated/SystemConfigSystemGroupIndex.vue') },
      { path: 'system_config_system_config_tab_list', name: 'SystemConfigSystemConfigTabList', component: () => import('../components/generated/SystemConfigSystemConfigTabList.vue') },
      { path: 'system_config_system_group_list', name: 'SystemConfigSystemGroupList', component: () => import('../components/generated/SystemConfigSystemGroupList.vue') },
      { path: 'out', name: 'Out', component: () => import('../components/generated/Out.vue') },
      { path: 'out_interface', name: 'OutInterface', component: () => import('../components/generated/OutInterface.vue') },
      { path: 'system_maintain_clear_index', name: 'SystemMaintainClearIndex', component: () => import('../components/generated/SystemMaintainClearIndex.vue') },
      { path: 'system_maintain_system_log_index', name: 'SystemMaintainSystemLogIndex', component: () => import('../components/generated/SystemMaintainSystemLogIndex.vue') },
      { path: 'system_maintain_system_file_index', name: 'SystemMaintainSystemFileIndex', component: () => import('../components/generated/SystemMaintainSystemFileIndex.vue') },
      { path: 'system_maintain_system_cleardata_index', name: 'SystemMaintainSystemCleardataIndex', component: () => import('../components/generated/SystemMaintainSystemCleardataIndex.vue') },
      { path: 'system_maintain_system_databackup_index', name: 'SystemMaintainSystemDatabackupIndex', component: () => import('../components/generated/SystemMaintainSystemDatabackupIndex.vue') },
      { path: 'system_log', name: 'SystemLog', component: () => import('../components/generated/SystemLog.vue') },
      { path: 'system_user', name: 'SystemUser', component: () => import('../components/generated/SystemUser.vue') },

    ]
  }
]

const router = createRouter({
  history: createWebHistory(),
  routes
})

router.beforeEach((to, from, next) => {
  const token = localStorage.getItem('admin_token')
  if (to.meta.requiresAuth && !token) {
    next('/login')
  } else {
    next()
  }
})

export default router
